## Numpy Basic

In [82]:
import numpy as np

### data type
array의 dtype을 본다

In [3]:
arr = np.array([[1,2,3],[1,2,3]])

In [4]:
arr.dtype

dtype('int32')

.astype()으로 datatype을 변환 가능

In [9]:
arr = arr.astype(np.int32)

In [10]:
arr.dtype

dtype('int32')

In [12]:
arr = np.array([[1,2,3],[1,2,3]], dtype = np.uint8)

In [13]:
arr.dtype

dtype('uint8')

len(arr.shape)를 통해서 차원의 갯수를 확인 할 수 있지만, 아래와 같이 ndim을 통해 차원의 수를 return 가능

In [14]:
arr.shape

(2, 3)

In [15]:
len(arr.shape)

2

size 확인

In [17]:
arr.size

6

dtype 확인

In [18]:
arr.dtype

dtype('uint8')

### Reshape

In [19]:
arr.shape

(2, 3)

In [25]:
arr = arr.reshape([1,6]) # 2x3 = 1x6
arr.shape

(1, 6)

In [26]:
arr = np.array([[1,2,3],[1,2,3]])

In [29]:
arr = arr.reshape([1,1,6])
arr.shape

(1, 1, 6)

In [30]:
arr = np.array([[1,2,3],[1,2,3]])

In [31]:
arr = arr.reshape([6])
arr.shape

(6,)

Reshape -1 활용

In [34]:
arr = arr.reshape(-1) # 남는거(?)
arr.shape

(6,)

In [35]:
arr = arr.reshape(-1,3) #미지수라고 생각하면 편할듯
arr.shape

(2, 3)

random array 생성

In [41]:
arr = np.random.randn(8,8)
arr

array([[ 0.86857358,  0.83731018, -0.85204534, -0.32610726, -1.42596968,
        -1.45258318,  2.12817485, -0.39561038],
       [-1.15522022, -0.20064461, -0.87433757,  1.25513933,  0.42908901,
        -0.95187938, -0.27880026,  1.59633393],
       [-1.69854586,  0.54936413, -0.14449453, -0.3419775 , -0.91766773,
         0.0292096 , -0.95483828,  1.48767069],
       [ 1.249622  , -0.67684131,  0.54390456,  0.60287321, -1.42479349,
         0.50026045,  0.88477278, -0.31789974],
       [ 0.72012923,  1.0605936 , -1.90972617, -0.0116191 ,  0.06600189,
         0.30196646,  1.43674187,  1.31063749],
       [-0.11622199,  0.14617091,  0.5820509 ,  0.87872165,  0.74127098,
         1.30670231, -0.66524176,  0.88477808],
       [-1.1037263 , -0.17254787,  0.98591775,  0.43508803, -1.42125589,
         0.98827979,  1.02068398,  0.09964638],
       [ 0.36347049,  2.59404759,  0.00437578, -0.30085374, -0.82390822,
        -1.35820399, -1.07016493,  0.94075813]])

In [43]:
arr = arr.reshape([32,2])
arr

array([[ 0.86857358,  0.83731018],
       [-0.85204534, -0.32610726],
       [-1.42596968, -1.45258318],
       [ 2.12817485, -0.39561038],
       [-1.15522022, -0.20064461],
       [-0.87433757,  1.25513933],
       [ 0.42908901, -0.95187938],
       [-0.27880026,  1.59633393],
       [-1.69854586,  0.54936413],
       [-0.14449453, -0.3419775 ],
       [-0.91766773,  0.0292096 ],
       [-0.95483828,  1.48767069],
       [ 1.249622  , -0.67684131],
       [ 0.54390456,  0.60287321],
       [-1.42479349,  0.50026045],
       [ 0.88477278, -0.31789974],
       [ 0.72012923,  1.0605936 ],
       [-1.90972617, -0.0116191 ],
       [ 0.06600189,  0.30196646],
       [ 1.43674187,  1.31063749],
       [-0.11622199,  0.14617091],
       [ 0.5820509 ,  0.87872165],
       [ 0.74127098,  1.30670231],
       [-0.66524176,  0.88477808],
       [-1.1037263 , -0.17254787],
       [ 0.98591775,  0.43508803],
       [-1.42125589,  0.98827979],
       [ 1.02068398,  0.09964638],
       [ 0.36347049,

3차원으로 늘리기

In [44]:
arr = arr.reshape(-1,2,1)

In [45]:
arr.shape

(32, 2, 1)

In [46]:
arr = arr.reshape(-1,2,1,1,1,1,1)

In [47]:
arr

array([[[[[[[ 0.86857358]]]]],




        [[[[[ 0.83731018]]]]]],





       [[[[[[-0.85204534]]]]],




        [[[[[-0.32610726]]]]]],





       [[[[[[-1.42596968]]]]],




        [[[[[-1.45258318]]]]]],





       [[[[[[ 2.12817485]]]]],




        [[[[[-0.39561038]]]]]],





       [[[[[[-1.15522022]]]]],




        [[[[[-0.20064461]]]]]],





       [[[[[[-0.87433757]]]]],




        [[[[[ 1.25513933]]]]]],





       [[[[[[ 0.42908901]]]]],




        [[[[[-0.95187938]]]]]],





       [[[[[[-0.27880026]]]]],




        [[[[[ 1.59633393]]]]]],





       [[[[[[-1.69854586]]]]],




        [[[[[ 0.54936413]]]]]],





       [[[[[[-0.14449453]]]]],




        [[[[[-0.3419775 ]]]]]],





       [[[[[[-0.91766773]]]]],




        [[[[[ 0.0292096 ]]]]]],





       [[[[[[-0.95483828]]]]],




        [[[[[ 1.48767069]]]]]],





       [[[[[[ 1.249622  ]]]]],




        [[[[[-0.67684131]]]]]],





       [[[[[[ 0.54390456]]]]],




        [[[[[ 0.60287321]]]]]

### Ravel

In [48]:
arr.shape

(32, 2, 1, 1, 1, 1, 1)

In [49]:
arr = arr.ravel()
arr.shape

(64,)

arr의 차원을 1로 바꿔줌
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨

arr.reshape(-1)와 같음

In [51]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음

In [53]:
arr.shape

(64,)

In [57]:
arr=np.expand_dims(arr,0)
arr.shape

(1, 64)

In [58]:
arr = arr.ravel()

In [59]:
arr.shape

(64,)

In [60]:
arr= np.expand_dims(arr,-1)

In [61]:
arr.shape

(64, 1)

In [62]:
arr= np.expand_dims(np.expand_dims(arr,-1),0)

In [63]:
arr.shape

(1, 64, 1, 1)

### zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [67]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
zeros = np.zeros(1)
zeros

array([0.])

In [69]:
ones = np.ones([10])
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
ones = np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
ones *5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [85]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [86]:
arr = np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [87]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [88]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Index

In [89]:
nums = [1,2,3,4,5]

In [90]:
nums[2:]

[3, 4, 5]

In [91]:
arr[1]

array([3, 4, 5])

In [92]:
arr[1][2]

5

In [93]:
arr[1,2]

5

### Slicing

In [94]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [95]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

### Boolean Indexing

In [96]:
data = np.random.randn(3,3)
data

array([[ 0.50571396, -0.81996026,  0.6801393 ],
       [-0.2045717 , -0.29116343,  0.43247603],
       [ 2.23153643,  0.97708933, -0.50492839]])

In [97]:
data <= 0

array([[False,  True, False],
       [ True,  True, False],
       [False, False,  True]])

In [98]:
data[data <= 0]

array([-0.81996026, -0.2045717 , -0.29116343, -0.50492839])

In [99]:
data[data <= 0] = 1

In [100]:
data

array([[0.50571396, 1.        , 0.6801393 ],
       [1.        , 1.        , 0.43247603],
       [2.23153643, 0.97708933, 1.        ]])

### Broadcast

tensorflow나 python로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산하려는 서로 다른 두개의 행렬의 shape가 같지 않고,
한쪽의 차원이라도 같거나 또는 값의 개수가 한개 일 때
이를 여러 복사를 하며 연산을 함

In [101]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [103]:
arr * 9

array([[ 0,  9, 18],
       [27, 36, 45],
       [54, 63, 72]])

In [106]:
arr + np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [105]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Math Function

In [107]:
arr +10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [108]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [109]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [110]:
np.add(arr,1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
np.multiply(arr,3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [117]:
arr = np.random.randint(2, size = 27).reshape(3,3,3)
arr_2 = np.random.randint(2, size = 9).reshape(3,3)

In [118]:
arr

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 1, 1],
        [1, 0, 1],
        [0, 1, 1]]])

In [120]:
arr_2

array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [121]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [122]:
arr + arr_2

array([[[2, 0, 0],
        [0, 1, 1],
        [0, 0, 1]],

       [[2, 0, 0],
        [0, 1, 1],
        [0, 0, 1]],

       [[2, 1, 1],
        [1, 0, 2],
        [0, 1, 1]]])

In [123]:
np.sum(arr)

13

In [124]:
np.sum(arr+arr_2)

19

In [125]:
np.max(arr+arr_2)

2

In [126]:
np.min(arr+arr_2)

0

In [127]:
np.max(arr+arr_2,0)#0차원에서 제일 큰 값 반환

array([[2, 1, 1],
       [1, 1, 2],
       [0, 1, 1]])

In [128]:
np.sum(arr + arr_2,0)

array([[6, 1, 1],
       [1, 2, 4],
       [0, 1, 3]])

In [129]:
np.sum(arr + arr_2,-1)

array([[2, 2, 1],
       [2, 2, 1],
       [4, 3, 2]])

In [130]:
np.mean(arr)

0.48148148148148145

In [133]:
arr = np.array([1,6,3,7,3,2,9,4,0,2])

In [134]:
np.argmax(arr) #6번째 인자가 가장 크다는 것

6

In [135]:
np.argmin(arr)

8

In [136]:
arr = np.array([3,5,6,6,3,3,1])

In [137]:
np.unique(arr)

array([1, 3, 5, 6])