In [34]:
import numpy as np
import tensorflow as tf

#### Tensor 생성
- []
 - List 생성

In [2]:
[1,2,3]

[1, 2, 3]

In [3]:
[[1,2,3,],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

#### Array 생성
- tuple이나 list 둘 다 np.array()로 씌어서 array를 만들 수 있음

In [4]:
arr = np.array([1,2,3])

In [5]:
arr.shape

(3,)

In [6]:
arr = np.array([[1,2,3],[1,2,3]])

In [7]:
arr.shape

(2, 3)

#### Tensor생성
- tf.constant()
 - list -> tensor

In [8]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

- tf.constant()
 - tuple -> Tensor

In [10]:
tf.constant(((1,2,3),(1,2,3)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

- tf.constant()
 - Array-> Tensor

In [11]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [13]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

#### Tensor에 담긴 정보 확인
- shape 확인

In [14]:
tensor.shape

TensorShape([3])

- data type 확인
 - 주의 : tensor 생성 할 때도 data type을 정해주지 않기 때문에 data type에 대한 혼동이 올 수도 있음
 - Data type에 따라 모델의 무게나 성능 차이에도 영향을 줄 수 있음

In [15]:
tensor.dtype

tf.int32

- data type 정의

In [18]:
tensor = tf.constant([1,2,3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

- data type 변환
 - Numpy 에서 astype()을 주었듯이, TensorFlow에서는 tf.cast를 사용

In [19]:
arr = np.array([1,2,3], dtype=np.float32)

In [21]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [22]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [23]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

- Tensor에서 Numpy 불러오기
 - .numpy()

In [25]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

- Tensor에서 Numpy 불러오기
 - np.array()

In [24]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

type()를 사용하여 numpy array로 변환된 것 확인

In [26]:
type(tensor.numpy())

numpy.ndarray

In [27]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

### 난수 생성
- Normal Distribution은 중심 극한 이론에 의한 연속적인 모양
- Uniform Distribution은 중심 극한 이론과는 무관하며 불연속적이며 일정한 분포

- numpy에서는 normal distribution을 기본적으로 생성
 - np.random.randn()

In [28]:
np.random.randn(9)

array([-0.61774808, -0.13815255,  0.31256786,  1.59309739, -0.95133846,
       -0.46685174, -0.34119921,  0.63841588, -1.38085814])

- tf.random.normal
 - tensorFlow에서 Normal Distribution 

In [32]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.01574558, -0.64727294, -1.7632283 ],
       [-0.14933878,  1.9261774 ,  0.7179776 ],
       [ 0.7938656 ,  0.34600607, -0.7655556 ]], dtype=float32)>

- tf.random.uniform
 - TensorFlow에서 Uniform Distribution

In [36]:
tf.random.uniform([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.0314765 , 0.9046031 , 0.13188243, 0.9297272 ],
       [0.40608513, 0.28144217, 0.27565122, 0.5054107 ],
       [0.84366083, 0.10148752, 0.6530014 , 0.50379384],
       [0.21601057, 0.5741818 , 0.38386738, 0.7085527 ]], dtype=float32)>