### Tensor

#### Scalar - Vector - Matrix - Tensor
딥러닝을 하다보면 Tensor라는 개념이 많이 나올 것이다.
그중 Tensor의 개념을 잘 이해하는 것이 중요한데,
딥러닝에서는 주로 고차원적인 데이터를 많이 사용할 것이기 때문

Numpy는 그런 고차원적인 데이터를 다루기 쉽게 만들어져 있어 딥러닝을 하시게 된다면 늘 접하게 될 것임.

In [1]:
import numpy as np

### 0차원 : Scalar
- numpy array는 1 또는 5,10과 같이 숫자 데이터를 array화 해줄 수 있음

In [2]:
arr = np.array(5)

In [4]:
arr.shape #모양
# Scalar로 들어갔을 때는 shape가 아무것도 없는 것으로 나온다

()

In [5]:
arr.ndim #차원의 개수

0

### 1차원 : Vector
- 숫자가 10과 같이 하나만 들어간다고 해도 [] 리스트를 한번 씌우게 되면 차원이 생긴다.
- 이때는 1차원이 되는건데 numpy에서 shape를 표현 할 때 (1)이 아닌 (1,)이런 식으로 표현하게 됨

In [10]:
arr = np.array([5])
arr

array([5])

In [11]:
arr.shape

(1,)

- 명심해야 할 것이 있는데 위의 (3.)에서 3은 3이라는 값이 들어간 것이 아닌 shape라는 것을 명심
- 1차원에서 3개의 값이 들어갔다는 의미
- 해석하자면 1차원에 3개의 값(value)가 들어감

In [12]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [13]:
arr.shape

(3,)

In [14]:
#(3) -> (3.)

### 2차원 Matrix
대괄호를 추가적으로 씌우면 차원이 추가적으로 하나 생김

In [15]:
arr = np.array([[1,2,3]])
arr.shape

(1, 3)

In [16]:
arr = np.array([[1,2,3],[1,2,3],[1,2,3]])
arr.shape

(3, 3)

In [17]:
np.array(([10]))

array([10])

In [19]:
arr = np.array([[10]])
arr.shape

(1, 1)

In [20]:
arr.ndim

2

### 다차원 : Tensor

In [25]:
arr = np.array([[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]],[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]])
arr

array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])

In [26]:
arr.shape

(2, 2, 3, 3)

### Array 연산